### ISSUE TITLE
Remove irrelevant link

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-website#100]
On the entry point of the website, https://opencensus.io/overview/index.html, the top link says 

"HERE IS A GREAT ARTICLE THAT EXPLAINS TRACING CONCEPTS"

This is so irrelevant here and needs to be added to the blog page. Please remove this link from this page.

**Comment by adamgarza** [comment]
Pritam requested the placement. Not sure which direction to take at this point.

**Comment by rakyll** [comment]
I talked to Pritam, this is not a good placement for this link. Especially with the existing text.
