### ISSUE TITLE
Get content for opencensus-website/content/go.md from opencensus-go README

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-website#166]
`opencensus-website/content/go.md` looks like an out-of-date copy of the opencensus-go README.md. 

Can we make the build system for the website import this from opencensus-go latest released version automatically?

**Comment by rakyll** [comment]
Can we instead make README linking to the website?

**Comment by ramonza** [comment]
I would prefer to keep all the content on the README, that's the first place I would go to look at a new project and it would annoy me to just be redirected to a website. Also, having code examples checked and versioned with the code is nice.

**Comment by rakyll** [comment]
Then, we should keep the content split. The language quickstart pages will be revised soon. We are temporarily using the README content for Go because we have no other better content.

**Comment by rakyll** [comment]
Instead of this, maybe we should remove the go page and point the links to the repo.
