### ISSUE TITLE
Add new article to the blog

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-website#167]
Monitoring HTTP Latency with OpenCensus and Stackdriver
https://medium.com/google-cloud/monitoring-http-latency-with-opencensus-and-stackdriver-bf561608e81a

As a note, can we make publishing new content to the blog page a little bit easier? It requires readjustment of the table for each new item. Replacing the table with floating divs can improve this problem.

**Comment by adamgarza** [comment]
Yes, this is my goal. The current process is not efficient.

**Comment by rakyll** [comment]
Fixed via 75a82b1c9590256dfb9bdc4413b8e5b6f19151ab.
