### ISSUE TITLE
Amazon X-RAY roadmap.md

### ISSUE THREAD

**Issue by MaerF0x0** [census-instrumentation/opencensus-website#182]
WRT https://opencensus.io/roadmap/ 

I thought there was at least golang support for amazon X-ray ?  

Emmanuel Odeke from Orijtech Gave his talk  Planet-Scale Observability – Distributed Tracing and Monitoring with OpenCensus at https://www.meetup.com/golangsf/events/249471121/

**Comment by ramonza** [comment]
There is, see: https://github.com/census-ecosystem/opencensus-go-exporter-aws
