### ISSUE TITLE
Add users page

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-website#217]
We have a lot of users now but the community is not aware, it would be cool to have a page of publicly known OC users.

**Comment by odeke-em** [comment]
Great idea @rakyll!

/cc @hvent90

**Comment by rakyll** [comment]
Few suggestions:

* Stackdriver Monitoring and Trace
* Google Cloud Platform
* Oracle Fn Project
* Knative
* Istio
* Skia (skia.org)
* Microsoft
* Stratumn
* Go Cloud
* Trillian (google/trillian)

**Comment by odeke-em** [comment]
Awesome, thanks for the confirmation @greggdonovan!

**Comment by ardan-bkennedy** [comment]
@odeke-em thanks for the heads up. I created a PR and signed the agreement.

**Comment by odeke-em** [comment]
Awesome, thanks @ardan-bkennedy, the page is now live and thank you for using OpenCensus!
