### ISSUE TITLE
content: add HTTP section 

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#222]
This issue is the cousin of https://github.com/census-instrumentation/opencensus-website/issues/221 but instead for HTTP.

Some months ago I wrote a guide for OpenCensus for Go HTTP developers https://medium.com/@orijtech/hello-world-for-web-servers-in-go-with-opencensus-29955b3f02c6

but we need to extract that information and make a section say "HTTP integration" and in it provide guides for the various languages.

For Java, we'll need some input/help from @bogdandrutu @HailongWen @hyangah 
while for Python, we'll need some input/help from @liyanhui1228 @eduardoemery 
while for C++, we'll need some input/help from @g-easy @isturdy 
and for others please feel free to pitch in.

**Comment by g-easy** [comment]
C++ doesn't have a standard HTTP server like e.g. https://godoc.org/net/http

Our existing examples use civetweb to publish the `/metrics` endpoint for Prometheus. We should write an example server and see what instrumentation and header business (e.g. trace context) is required.

**Comment by odeke-em** [comment]
For starters, I've mailed a guide for net/http.Client https://github.com/census-instrumentation/opencensus-website/pull/476 and will add one subsequently for net/http.Server.

**Comment by odeke-em** [comment]
And I've also mailed the guide for net/http.Server with https://github.com/census-instrumentation/opencensus-website/pull/477

**Comment by odeke-em** [comment]
Alright, this section was started and we can keep adding more as we please.
