### ISSUE TITLE
Scrollbars in Table Cells

### ISSUE THREAD

**Issue by nikmd23** [census-instrumentation/opencensus-website#235]
On pages that shows tables, like the Roadmap and Language Support pages, each table cell shows scrollbars.

Here's an illustrative screenshot:

![image](https://user-images.githubusercontent.com/199026/44163124-1863f300-a088-11e8-8083-01f898e0070a.png)

It'd be better if the cells did not have show scroll bars.

I've been able to replicate this issue on Windows 10, using both Chrome 67 and Edge 17. Zoom level of the page does not effect this issue, scrollbars appear at all zoom levels.

**Comment by hvent90** [comment]
Thanks for making an issue. This is due to `overflow: scroll` CSS property. I'll push up a PR.

**Comment by nikmd23** [comment]
I'm seeing this on a few other pages as well:
![image](https://user-images.githubusercontent.com/199026/45518790-4d8f5e00-b778-11e8-9dac-820c33e88b86.png)
![image](https://user-images.githubusercontent.com/199026/45518866-95ae8080-b778-11e8-95d0-99b079fc8d7f.png)
![image](https://user-images.githubusercontent.com/199026/45518917-c0003e00-b778-11e8-8050-ebba381a1459.png)
![image](https://user-images.githubusercontent.com/199026/45518927-cd1d2d00-b778-11e8-8cf1-9024b2e5fd76.png)
![image](https://user-images.githubusercontent.com/199026/45518933-d60dfe80-b778-11e8-9bce-492b71c7c01e.png)
![image](https://user-images.githubusercontent.com/199026/45518993-06559d00-b779-11e8-9b27-c92dbec49950.png)
![image](https://user-images.githubusercontent.com/199026/45519025-1ec5b780-b779-11e8-9610-c9af08ca6595.png)
![image](https://user-images.githubusercontent.com/199026/45519042-2c7b3d00-b779-11e8-8c14-c5d9c749aae6.png)

There's more. I think this effects all tables.

**Comment by hvent90** [comment]
This was intentional and noted in the PR (#236)

Note: this comment is just to provide context, I am not trying to curtail any critique
