### ISSUE TITLE
Provide definitions of terms

### ISSUE THREAD

**Issue by jadekler** [census-instrumentation/opencensus-website#24]
It would help _tremendously_ to define what a trace, a span, a measurement, view, aggregation, stat, and any other technical terms mean. I think most people have a sense, but putting it on paper would clear up a lot of confusion.

**Comment by rakyll** [comment]
We will have a new website soon with all these concepts explained soon. For now, you can refer to the specs for tracing and tags, see github.com/census-instrumentation/opencensus-specs.

**Comment by jadekler** [comment]
Ah! Fantastic. Thanks @rakyll
