### ISSUE TITLE
content: Notes should be attention grabbing

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#247]
Reported offline by more than 3 users, the current notes that ask users to install pre-requisites such as Stackdriver

e.g. from https://opencensus.io/quickstart/go/tracing/

![screen shot 2018-08-19 at 11 20 50 pm](https://user-images.githubusercontent.com/4898263/44323382-88ff6c80-a406-11e8-8cac-7d78baf884bd.png)

Quickstart users have still missed the installation notes and these are quite experienced engineers who work at  some of the companies that produce the products that are in the pre-requisites.

/cc @hvent90 @adamgarza for ideas on how to make this stand out.

**Comment by hvent90** [comment]
What does everyone think of this?

<img width="909" alt="screen shot 2018-08-20 at 9 55 27 am" src="https://user-images.githubusercontent.com/5974764/44354625-32724c80-a45f-11e8-829f-bc613cee7293.png">

**Comment by hvent90** [comment]
Another:

<img width="827" alt="screen shot 2018-08-20 at 9 58 55 am" src="https://user-images.githubusercontent.com/5974764/44354815-af9dc180-a45f-11e8-9dca-3c8a66f55aaf.png">

**Comment by hvent90** [comment]
And for Python:
<img width="929" alt="screen shot 2018-08-20 at 10 02 56 am" src="https://user-images.githubusercontent.com/5974764/44355031-45d1e780-a460-11e8-8f6b-9187ce61672a.png">
