### ISSUE TITLE
undefined: io, https://opencensus.io/quickstart/go/metrics/#getting-started

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-website#256]
Getting Started, first example. import io is missing.
Error : 
# command-line-arguments
./repl.go:20:14: undefined: io

**Comment by mayurkale22** [comment]
@odeke-em FYA

**Comment by odeke-em** [comment]
Awesome, thank you @mayurkale22, I've mailed out https://github.com/census-instrumentation/opencensus-website/pull/257.
