### ISSUE TITLE
Logo images at top of articles overflow

### ISSUE THREAD

**Issue by hvent90** [census-instrumentation/opencensus-website#290]
![screen shot 2018-08-28 at 3 30 59 pm](https://user-images.githubusercontent.com/5974764/44754629-71477880-aad7-11e8-8a0f-781d081ab4b0.png)

**Comment by hvent90** [comment]
Images currently have a max-width of 500px to prevent them from getting too tall (as some are vertically gifted).

I may extract all of the logos to a shortcode that will have a structure as such:

```html
<!-- Usage -->
{{% article-logo src="/images/node-opencensus.png" %}

<!-- Shortcode -->
<!-- CSS would be extracted to content.css -->
<div style="max-width: 500px">
    <img max-width: "100%" src="/images/node-opencensus.png">
</div>
```

**Comment by hvent90** [comment]
I think reconsolidating the logo in to the page header makes for a cleaner flow:

![screen shot 2018-08-29 at 1 17 43 pm](https://user-images.githubusercontent.com/5974764/44813159-0311bd00-ab8e-11e8-8992-3e822bec4c89.png)

I'll look in to potentially adding this as a front-matter field.

**Comment by odeke-em** [comment]
@hvent90 I believe your PR #294 fixes this problem?

**Comment by hvent90** [comment]
Sure does! Thanks @odeke-em
