### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-website#3]
https://opencensus.io/ is failing with a certificate error. We need to support and probably default to HTTPS.

**Comment by bogdandrutu** [comment]
@tags07 ping on this.

**Comment by MarinaYoussef9** [comment]
That's not about changing the baseURL from http to https, right? ( I think Hugo already handle supporting HTTPS)

**Comment by ahmetb** [comment]
This seems to have resolved in the meanwhile.
