### ISSUE TITLE
content/guides/exporters/supported-exporters/Go/Jaeger.md out of date

### ISSUE THREAD

**Issue by black-adder** [census-instrumentation/opencensus-website#304]
`collectorEndpointURI := "http://localhost:9411"` is the zipkin payload endpoint that jaeger collector exposes, it should instead point to `http://localhost:14268` which is the jaeger payload endpoint. Otherwise the clients will send jaeger payload to the zipkin endpoint resulting in: `Error when uploading spans to Jaeger: failed to upload traces; HTTP status code: 404`

**Comment by voutasaurus** [comment]
Addressed by https://github.com/census-instrumentation/opencensus-website/pull/305

**Comment by voutasaurus** [comment]
Sorry I didn't see this issue before making my PR

**Comment by songy23** [comment]
Thanks for the fix!
