### ISSUE TITLE
content/*/integrations: add Go-Kit

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#310]
We'll need to provide a guide for the Go-Kit integration.

Please take a look @basvanbeek

**Comment by basvanbeek** [comment]
no problem. will work on that

**Comment by basvanbeek** [comment]
initial version available in PR https://github.com/census-instrumentation/opencensus-website/pull/336

**Comment by odeke-em** [comment]
Thank you for working on this @basvanbeek! You've fixed this with PRs:
* https://github.com/census-instrumentation/opencensus-website/pull/336
* https://github.com/census-instrumentation/opencensus-website/pull/341
