### ISSUE TITLE
all: ensure Stackdriver metrics reporting happens in intervals of >=60s

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#314]
Originally from https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/36,
@rimey reported an important point and a consequence https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/36#issuecomment-418476064

We've used a couple of seconds since some of the examples ran for a very short time but let's fix that for any Stackdriver examples and ensure that the examples run for >=60s as recommended by https://cloud.google.com/monitoring/custom-metrics/creating-metrics#writing-ts

**Comment by songy23** [comment]
FYI in Java the default interval for exporting to Stackdriver Monitoring is 60 seconds: https://github.com/census-instrumentation/opencensus-java/blob/43651556393859b342d6db65b11aa6dca61b3678/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java#L71.

**Comment by odeke-em** [comment]
Thanks @songy23!

This is a legit problem that's causing confusion for many folks as in https://github.com/census-instrumentation/opencensus-go/issues/909 and even reported offline by a tech writer. Let me update this ASAP.
