### ISSUE TITLE
Blog section killed?

### ISSUE THREAD

**Issue by nikmd23** [census-instrumentation/opencensus-website#324]
It seems like the blog page, which had many posts in the old design, are now missing.

Are those posts coming back? Does it make sense to submit new posts?

**Comment by songy23** [comment]
There's a new `Blogs` tab here: https://opencensus.io/blogs/. Feel free to submit new posts there. I believe most of the old blog posts were moved to other sections, for example https://opencensus.io/guides/integrations/google_cloud/google_cloud_spanner/go/.

/cc @odeke-em

**Comment by odeke-em** [comment]
Hello @nikmd23, great to catch you here!

So not really, they were never killed just extracted and placed: the old "blog posts" were basically guides as @songy23 has mentioned above and weren't really blogposts. If there is an actual blogpost that you have in mind, please feel free to send a PR :)

**Comment by nikmd23** [comment]
🙁

Humm. Is there a reason why only "most" of the blog posts were moved? There certainly was post content that is now 100% missing. Obviously I'm biased since one of those was the one that I wrote.

It seems to me that blog posts that didn't fit in as guides could have been left as posts in the blog section.

Posts being removed doesn't instill a lot of confidence to write on the OpenCensus website again.

**Comment by odeke-em** [comment]
>Humm. Is there a reason why only "most" of the blog posts were moved? 

My apologies @nikmd23! It was just an innocent oversight on our side, no malice intended. It's been mostly @hvent90 and I working on the website revamp which we had to get out in less than 2 weeks. 

>Posts being removed doesn't instill a lot of confidence to write on the OpenCensus website again.

Please direct me to your blogpost and we can make amends -- apologetically, this wasn't intentional but rather a lack of hands to cover everything.

**Comment by odeke-em** [comment]
@hvent90 would you mind prioritizing looking at the content in https://github.com/census-instrumentation/opencensus-website/blob/701f94daaa6358b9551ab2da40298e8e89bf5a24/content/blog.md and creating blog entries for it? Thank you

**Comment by hvent90** [comment]
@nikmd23,

I apologize for the neglect of your work and I take responsibility. Like @odeke-em said, we were in crunch time to get out a redesign before an incoming deadline, thus leading to my slip with missing your work.

I know it doesn't feel good to have your effort feel trivialized or neglected, and I apologize. I will put up a pull request shortly that migrates the rest of the blog content.

Thanks for speaking up.

Cheers

**Comment by nikmd23** [comment]
Hey guys, no need to be apologetic. I totally understand deadlines and that pressure.

I really was wondering "why". I thought maybe we were transitioning the blogs to another system that provided RSS feeds or something like that.

Thanks for going through and adding the missing content. I'll be submitting some docs updates and a new blog soon.

Thanks!

**Comment by odeke-em** [comment]
@nikmd23 thank you very much for raising this issue. The fast and kind @hvent90 has migrated the content over back, please visit https://opencensus.io/blogs/ and for other blogposts please feel free to send a PR.

Also please feel free to reopen this PR if we need updates or open a separate issue.
