### ISSUE TITLE
quickstart/python: complete stats tutorial

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#354]
The Python stats quickstart is currently marked as incomplete as we were waiting for some updates to the Python stats package for the various transports and exporters to be implemented.

However, these are all addressed with

Item|URL
---|---
Prometheus stats exporter|https://github.com/census-instrumentation/opencensus-python/pull/294
Stats changes, transports updates|https://github.com/census-instrumentation/opencensus-python/pull/256
Stackdriver stats exporter|https://github.com/census-instrumentation/opencensus-python/pull/250

/cc @PikBot

**Comment by songy23** [comment]
Bumping this up. Looks like tutorials on Python Stackdriver Stats exporter and Prometheus exporter are still missing.

**Comment by odeke-em** [comment]
@songy23 if I recall correctly the Prometheus exporter was buggy and couldn't export stats; also something was up with the Stackdriver stats exporter or we were waiting for metrics to be added. But sure let's try again this quarter.

**Comment by songy23** [comment]
Stackdriver is fixed in https://github.com/census-instrumentation/opencensus-python/pull/438 and Prometheus is fixed in https://github.com/census-instrumentation/opencensus-python/pull/440. Not sure whether we need to make a new release for OC-Python though.

**Comment by odeke-em** [comment]
Thank you for the updates @songy23! We'll definitely need to make updates if `pip install` is going to work with these new bug fixes.

**Comment by songy23** [comment]
We've cut a new release for OpenCensus-Python: https://github.com/census-instrumentation/opencensus-python/releases/tag/v0.2.0, hopefully it should unblock this issue now.

**Comment by odeke-em** [comment]
Perfect, thank you @songy23!
