### ISSUE TITLE
guides/integrations: include Microsoft Azure Application insights for Python

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#358]
Congratulations to Microsoft on their announcement of Application Insights as per https://twitter.com/SergeyKanzhelev/status/1044364650773532673 and in particular this content https://docs.microsoft.com/en-us/azure/application-insights/opencensus-python

I would be great to include a section under `guides/integrations/microsoft_azure` with the content of that blog post, code samples and screenshots like we have for Google Cloud integrations.

/cc @SergeyKanzhelev @lmolkova @reyang

**Comment by reyang** [comment]
@nikmd23

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-website/pull/396.
