### ISSUE TITLE
Quickstart/Node.js: 404 Page not found

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-website#364]
Way to reproduce: Go to: https://opencensus.io/quickstart/node.js/, On the middle page, click on either Metrics or Tracing, you should see "404 Page not found". Both left panel links(Metrics or Tracing) are working as expected.

Current Link: https://opencensus.io/quickstart/node.js/quickstart/nodejs/metrics
Expected Link: https://opencensus.io/quickstart/nodejs/metrics/

**Comment by odeke-em** [comment]
Thanks for the report @mayurkale22!
