### ISSUE TITLE
content/languages & feature-matrix: Update C# progress.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-website#379]
As I noticed, [opencensus-csharp](https://github.com/census-instrumentation/opencensus-csharp) already has support for Tracing, Tags and Stats, and a lot of exporters (Zipkin/Prometheus/Stackdriver). Please update the current status of C# on https://opencensus.io/community/roadmap/.

/cc @simonz130

**Comment by odeke-em** [comment]
Great, thanks for filing this @songy23!

As @songy23 has noted, let's update the roadmap but also quickstarts too and exporters if possible. Unfortunately I don't know any C# so couldn't work on that, but I believe the format of how to make those additions can be duplicated from the other languages :)

**Comment by simonz130** [comment]
Is there a plan to have the quickstarts code not inline but rather embedded snippet from github?

**Comment by songy23** [comment]
I filed a separate issue for adding quick start and guides on C#: https://github.com/census-instrumentation/opencensus-website/issues/381. I'll update the language and exporter progress page first, since that's very straightforward :)
