### ISSUE TITLE
stats/Measure: incorrect URLs for "View" and "Aggregation"

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-website#419]
https://opencensus.io/stats/measure/

Hyperlinks for "View" and "Aggregation" are incorrect:
A View couples the Measurement produced by a Measure, with an Aggregation and optionally Tags to produce metrics.

Should be: "views" (with -s) and "aggregations" (with -s)

https://opencensus.io/stats/views
https://opencensus.io/stats/views/#aggregations

**Comment by odeke-em** [comment]
Hello @DazWilkin, thank you reporting this URL mismatch and great to hear from you!

For sure, I'll update those links right now.

**Comment by odeke-em** [comment]
In about 2 minutes or so, the website will be redeployed with this fixed as per https://github.com/census-instrumentation/opencensus-website/pull/422. Thank you again for the report @DazWilkin and please feel free to send over more feedback!
