### ISSUE TITLE
exporters/*: old links broken after website revamp

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-website#423]
Blog: https://www.honeycomb.io/blog/a-new-way-to-get-traces-into-honeycomb-collaboration-with-opencensus/

OpenCensus exporter link : https://opencensus.io/guides/exporters/supported-exporters/go/honeycomb/

**Comment by mayurkale22** [comment]
Same here, https://opencensus.io/guides/exporters/supported-exporters/java/stackdriver-stats/

**Comment by odeke-em** [comment]
Gotcha, am going through all the exporters and fixing the old aliases. PR should be up in 30 minutes or less :)

**Comment by odeke-em** [comment]
I've mailed https://github.com/census-instrumentation/opencensus-website/pull/424 for Go and Java. Other languages coming as an iteration.

**Comment by odeke-em** [comment]
Alright, with all those PRs merged, we've touched on every alias in exporters/ and this issue can be closed!

Thank you @mayurkale22 for the report!
