### ISSUE TITLE
community: add our code of conduct

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#436]
We've got a code-of-conduct as per https://github.com/census-instrumentation/opencensus-specs/blob/3ae56084daed005042c82939eda43a42c268c5b0/code-of-conduct.md

Let's also bring it here to community, it should live on the website under community.
Raised offline by @shahprit, thank you!

**Comment by shahprit** [comment]
@jparsana

**Comment by songy23** [comment]
It's better to have code of conduct as a top-level web page instead of just linking to Github repo.

**Comment by jparsana** [comment]
Sure I will create a different page and put it under 'community'...

**Comment by odeke-em** [comment]
Added by @mtwo in PR https://github.com/census-instrumentation/opencensus-website/pull/453 and the link is https://opencensus.io/conduct/ which coincidentally matches what the Go project uses too https://golang.org/conduct
