### ISSUE TITLE
some C++ code snippets are broken or not accurate 

### ISSUE THREAD

**Issue by StevenYCChou** [census-instrumentation/opencensus-website#488]
I found multiple parts of C++ code snippets are inaccurate.
1. [Stats/Metrics' Measure](https://opencensus.io/stats/measure/#3) C++ example won't compile (fixed in #487)
2. [Tag](https://opencensus.io/tag/) code snippets across TagKey, TagValue, TagMap/TagContext are all the same - it only explains how to define TagKey, but it doesn't show how the other 2 works.

**Comment by odeke-em** [comment]
Thank you @StevenYCChou!

I kindly page @hvent90 @g-easy

**Comment by odeke-em** [comment]
I exclusively made the Tag code snippets and most of the others, so I'll page more folks to help me check over this work. @StevenYCChou, please feel free to send more updates as verification of all these by one person is hard :)
