### ISSUE TITLE
guides/integrations: make integrations more visible by a move perhaps

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#552]
Raised offline by @shahprit but also something that I've noticed, the integrations aren't visible on our website's side bar
<img width="289" alt="screen shot 2019-01-28 at 3 31 23 am" src="https://user-images.githubusercontent.com/4898263/51833764-35deef00-22ad-11e9-8e1e-d9060fecebb7.png">

We need to perhaps move "Integrations" to make it a top level item i.e.
### Before
/guides/integrations

### After
/integrations

However, let's ensure that every moved page has aliases to old locations and that no links 404 whatsoever but also no unending recursion due to self references.

/cc @PikBot @hvent90

**Comment by shahprit** [comment]
Thanks for taking care of this @odeke-em
