### ISSUE TITLE
agent: add section on the OpenCensus Agent

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#560]
The agent is available at https://github.com/census-instrumentation/opencensus-service and we should add a top-level section for how to get it running and how to use it.

**Comment by songy23** [comment]
Should this be closed now?

**Comment by odeke-em** [comment]
>Should this be closed now?

@songy23 I guess now it can be but there is still more to add, though let's open concentrated issues for those ones. Thanks for the ping!
