### ISSUE TITLE
exporters/agent: document Java exporter

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#561]
Coming from #559, let's document how folks can use the OpenCensus Java agent exporter and provide an advisory for how to get folks migrating over to use that exporter.

**Comment by odeke-em** [comment]
Please take a look at https://github.com/census-instrumentation/opencensus-website/issues/559 which is now live at https://opencensus.io/exporters/supported-exporters/go/ocagent/

**Comment by alexamies** [comment]
Added an example of a custom Java exporter in  https://github.com/census-instrumentation/opencensus-website/pull/618
