### ISSUE TITLE
agent: update description to articulate what the agent does

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#596]
Coming here from feedback shared via email, we need the landing page for the agent https://opencensus.io/agent to articulate what it does and how to make it appealing but also intuitive.

Kindly paging everyone for suggestions and some eyes for the PR, but starting with
@tsloughter @songy23 @SergeyKanzhelev @nikmd23 @bogdandrutu @shahprit @mtwo

**Comment by tsloughter** [comment]
Looks great! 

A couple initial questions are what does it mean that it is "self monitored", is that referring to it reporting its own stats upstream as well? And was surprised to see the need for a prometheus lib to bind to a port for scraping to be an issue. Has that really been a problem for some that they are limited to ~65k scrape endpoints per-IP?

**Comment by songy23** [comment]
These could be good references: 
https://github.com/census-instrumentation/opencensus-service#introduction
https://github.com/census-instrumentation/opencensus-service/blob/master/DESIGN.md#goals

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-website/pull/603.
