### ISSUE TITLE
Java Tracing Quickstart refers to example repo 404 Not found

### ISSUE THREAD

**Issue by alexamies** [census-instrumentation/opencensus-website#632]
In the Java Tracing Quickstart
https://opencensus.io/quickstart/java/tracing/

Clone the example repository: git clone https://github.com/opencensus-otherwork/opencensus-java-by-example

but the repo either does not exist or is private.

**Comment by alexamies** [comment]
It should be 
https://github.com/opencensus-otherwork/opencensus-quickstarts.git

**Comment by alexamies** [comment]
I will work through the entire quickstart and the submit a PR with fixes to any problems that I find.

**Comment by bogdandrutu** [comment]
Fixed here https://github.com/census-instrumentation/opencensus-website/pull/633?

**Comment by alexamies** [comment]
Yes. thanks for linking.
