### ISSUE TITLE
agent: Add tutorial on exporting to Local Forwarder.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-website#644]
AFAIK Agent Exporters (e.g https://github.com/census-ecosystem/opencensus-go-exporter-ocagent) have the ability to export traces/metrics to Microsoft Local Forwarder. Consider adding a tutorial on this.

**Comment by songy23** [comment]
@SergeyKanzhelev Would you be able to help with this?

**Comment by reyang** [comment]
Please assign to me. Thanks.

**Comment by songy23** [comment]
I saw we already had tutorials for exporting to Azure Monitor in [Python](https://opencensus.io/exporters/supported-exporters/python/applicationinsights/) and [Go](https://opencensus.io/exporters/supported-exporters/go/applicationinsights/). Consider adding a similar tutorial to https://opencensus.io/service/exporters/. The config format for Local Forwarder in OC-Agent should be similar to https://opencensus.io/service/exporters/opencensus/, i.e:
```yaml
exporters:
  opencensus:
    endpoint: "local-forwarder-address"
```

**Comment by reyang** [comment]
We can close the issue given we are taking different approach now.

For Python, we have Azure Monitor exporter https://opencensus.io/exporters/supported-exporters/python/azuremonitor/.

For Go, we are building solution without having customers to install local forwarder. Eventually I will remove the local forwarder document from Golang.

**Comment by meastp** [comment]
@reyang Could you point to the issue/PR for this functionality in opencensus-service (agent or collector) as that is what this issue is about? It would be really helpful to be able to track this functionality... :)

**Comment by reyang** [comment]
@meastp need a quick clarification, which functionality did you mean?

**Comment by meastp** [comment]
@reyang I mean an explanation/documentation on how to export trace/metric-data to Azure Monitor with ocagent or occollector. :)

**Comment by reyang** [comment]
@meastp got it!

Today we don't have such support. I'll update this thread once we got something.

**Comment by meastp** [comment]
@reyang ok, thanks :)

**Comment by reyang** [comment]
@ChrisCoe

**Comment by ChrisCoe** [comment]
@meastp Yes, we are currently working on this functionality to export telemetrics to Azure Monitor without Local Forwarder. We are embracing a more open strategy to make it easier on the user's end.
