### ISSUE TITLE
sticky tab is large and creates cut-off/invalid image on index page

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-website#83]
I just took a look at the OpenCensus website and saw this
<img width="1078" alt="screen shot 2018-06-11 at 9 33 58 am" src="https://user-images.githubusercontent.com/4898263/41244727-bfd7bbfa-6d5a-11e8-9cc1-9a5976024ccd.png">

Seems like the top sticky tap was expanded a whole lot hence the scrollable area is smaller thus the underbite

**Comment by tags07** [comment]
Ya I noticed that too after we redid the website on hugo. We'll fix it soon.
+Adam @adamgarza

**Comment by adamgarza** [comment]
Yes, I will take a look & fix.

**Comment by rakyll** [comment]
This is fixed, closing the issue.
