### ISSUE TITLE
Guides and tutorials just pointing to GitHub

### ISSUE THREAD

**Issue by fabxc** [census-instrumentation/opencensus-website#86]
The footer of the website links to guides and tutorials. Those just link back to the GitHub org or the [opencensus-proto](https://github.com/census-instrumentation/opencensus-proto) repository.

**Comment by adamgarza** [comment]
Looking at the site footer:
guides link points to https://opencensus.io/guides/, but
tutorials link definitely needs correcting.
Will fix, thanks.

**Comment by fabxc** [comment]
Yes, but the three links listed on `guides/` don't point anywhere meaningful again.

**Comment by tags07** [comment]
We are working on restructuring docs. We'll have more meaningful content soon.

**Comment by rakyll** [comment]
Fixed via 21d7e9f954677b9cb2ddfc396ea193847309220b.
