### ISSUE TITLE
Pages not working locally with hugo 0.32

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-website#99]
I run the following:

```
$ hugo serve
```

Then, it starts the web server and serves the homepage. From the homepage, when I click on the links, there are all 404s. For example,

```
$ curl http://localhost:1313/quickstart/
404 page not found
```

**Comment by adamgarza** [comment]
My best guess is that this is an effect of the Hugo version issue.
Using v0.31.1:
`$ hugo serve`

The pages do render - seen below:
```
$ curl http://localhost:1313/quickstart/
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us">
...
```
Gopi and I planned on returning to this issue after zpages was completed. I will definitely require your assistance in solving this problem. It is currently listed on my backlog. Any guidance you can provide is appreciated.

**Comment by rakyll** [comment]
Thanks, this helped. I am keeping this around as a tracking bug.

**Comment by odeke-em** [comment]
No longer an issue so closing.
